# @package _global_

defaults:
  - _self_
  - data: default
  - policy: bc_transformer_policy
  - train: default
  - eval: default
  - lifelong: base
  - test: null

seed: 10000
use_wandb: false
wandb_project: "lifelong learning"
folder: /home/ydj/datasets # use default path
bddl_folder: /home/ydj/article/LIBERO/libero/libero/./bddl_files # use default path
init_states_folder: /home/ydj/article/LIBERO/libero/libero/./init_files # use default path
experiment_dir: /home/ydj # if specified, use this path; otherwise auto-generate
load_previous_model: false
device: "cuda"
task_embedding_format: "bert"
task_embedding_one_hot_offset: 1
bert_cache_dir: "/home/ydj/bert"
pretrain: false
pretrain_model_path: ""
benchmark_name: "LIBERO_SPATIAL"
